services:
  # DynamoDBのモックサーバー
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - dynamodb:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup"
  app:
    build:
      args:
        - target=dev
    volumes:
      - ./:/app
    environment:
      AWS_ENDPOINT: http://dynamodb:8000
      PORT: 80
    ports:
      - 8888:80
    command: air
  # AWS SDKのモックサーバー
  moto:
    image: motoserver/moto:latest
    network_mode: bridge
    ports:
      - 127.0.0.1:5000:5000/tcp
    volumes:
        - moto:/mnt/data  # ホストマシンの./moto_dataをコンテナ内の/mnt/dataにマウント
    environment:
      - MOTO_ENABLE_PERSISTENCE=true  # 永続化を有効にするオプション
      - MOTO_DATA_PATH=/mnt/data  # データ保存先ディレクトリのパスを指定
volumes:
  dynamodb:
    driver: local
  moto:
    driver: local
