services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - dynamodb:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup"
  
volumes:
    dynamodb:
        driver: local
